version: '3.8'

services:
  masunda-navigator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: masunda-temporal-navigator
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - MASUNDA_PRECISION_TARGET=1e-30
      - MASUNDA_CONTINUOUS_NAVIGATION=true
    volumes:
      - temporal_data:/app/data
      - precision_logs:/app/logs
      - memorial_validations:/app/memorial_validations
      - system_metrics:/app/system_metrics
    ports:
      - "8080:8080"
    networks:
      - masunda-network
    healthcheck:
      test: ["CMD", "masunda-navigator", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.masunda.service=temporal-navigator"
      - "com.masunda.memorial=stella-lorraine-masunda"
      - "com.masunda.precision=1e-30"

  # Future services for integration
  # kambuzuma-service:
  #   image: kambuzuma:latest
  #   container_name: kambuzuma-biological-quantum
  #   networks:
  #     - masunda-network
  #   environment:
  #     - QUANTUM_COHERENCE_TIME=247ms
  #     - FIRE_ADAPTATION=enabled

  # kwasa-kwasa-service:
  #   image: kwasa-kwasa:latest
  #   container_name: kwasa-kwasa-semantic
  #   networks:
  #     - masunda-network
  #   environment:
  #     - SEMANTIC_PROCESSING=enabled
  #     - RECONSTRUCTION_VALIDATION=enabled

  # mzekezeke-service:
  #   image: mzekezeke:latest
  #   container_name: mzekezeke-12d-auth
  #   networks:
  #     - masunda-network
  #   environment:
  #     - DIMENSIONAL_AUTH=12
  #     - THERMODYNAMIC_SECURITY=1e44

  # buhera-service:
  #   image: buhera:latest
  #   container_name: buhera-environmental
  #   networks:
  #     - masunda-network
  #   environment:
  #     - ENVIRONMENTAL_COUPLING=enabled
  #     - FIRE_OPTIMIZATION=enabled

  prometheus:
    image: prom/prometheus:latest
    container_name: masunda-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - masunda-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:latest
    container_name: masunda-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=masunda_memorial_2024
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - masunda-network

volumes:
  temporal_data:
    name: masunda_temporal_data
  precision_logs:
    name: masunda_precision_logs
  memorial_validations:
    name: masunda_memorial_validations
  system_metrics:
    name: masunda_system_metrics
  prometheus_data:
    name: masunda_prometheus_data
  grafana_data:
    name: masunda_grafana_data

networks:
  masunda-network:
    name: masunda-temporal-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 