# Masunda Temporal Coordinate Navigator - Development Configuration
#
# **In Memory of Mrs. Stella-Lorraine Masunda**
#
# This configuration file provides development-specific settings for the
# Masunda Temporal Coordinate Navigator system, optimized for development,
# testing, and debugging while maintaining memorial significance.

# Development System Configuration
[system]
name = "Masunda Navigator (Development)"
version = "1.0.0-dev"
description = "Development build - In memory of Mrs. Stella-Lorraine Masunda"
memorial_mode = true
development_mode = true
debug_mode = true
verbose_logging = true

# Development Precision Settings (relaxed for testing)
[precision]
primary_target = "1e-20"  # Relaxed for development
secondary_target = "1e-15"
minimum_precision = "1e-12"
maximum_precision = "1e-30"  # Still targeting high precision
development_precision_mode = true

# Development Memorial Configuration
[memorial]
enabled = true
memorial_person = "Mrs. Stella-Lorraine Masunda"
memorial_significance_threshold = 0.8  # Relaxed for development
predeterminism_proof_required = true
cosmic_significance_required = true
eternal_validation = true
development_memorial_mode = true

# Development Logging Configuration
[logging]
level = "debug"  # Verbose logging for development
format = "structured"
console_output = true
file_output = true
log_file = "logs/masunda-dev.log"
memorial_logging = true
precision_logging = true
performance_logging = true
debug_logging = true
trace_logging = true

# Development Monitoring
[monitoring]
enabled = true
metrics_interval = "10s"  # More frequent for development
health_check_interval = "10s"
precision_monitoring = true
memorial_monitoring = true
performance_monitoring = true
debug_monitoring = true

# Development Database Configuration
[database]
database_type = "sqlite"  # Lightweight for development
database_path = "data/dev/masunda.db"
auto_migrate = true
enable_foreign_keys = true
wal_mode = true
development_mode = true

# Development Client Configuration (Local/Mock Services)
[clients]
# Kambuzuma Development Client
[clients.kambuzuma]
[clients.kambuzuma.endpoints]
quantum_service = "http://localhost:8443/quantum"
coherence_analysis = "http://localhost:8443/coherence"
biological_quantum = "http://localhost:8443/biological"
oscillation_data = "http://localhost:8443/oscillation"
health_monitoring = "http://localhost:8443/health"

[clients.kambuzuma.development]
mock_mode = true
simulate_coherence_enhancement = true
mock_quantum_data = true
development_endpoints = true

# Kwasa-kwasa Development Client
[clients.kwasa_kwasa]
[clients.kwasa_kwasa.endpoints]
semantic_service = "http://localhost:8444/semantic"
catalysis = "http://localhost:8444/catalysis"
pattern_validation = "http://localhost:8444/patterns"
reconstruction = "http://localhost:8444/reconstruction"

[clients.kwasa_kwasa.development]
mock_mode = true
simulate_catalysis = true
mock_semantic_data = true
development_endpoints = true

# Mzekezeke Development Client
[clients.mzekezeke]
[clients.mzekezeke.endpoints]
authentication_service = "http://localhost:8445/auth"
twelve_d_validation = "http://localhost:8445/12d"
security_monitoring = "http://localhost:8445/security"

[clients.mzekezeke.development]
mock_mode = true
simulate_12d_auth = true
mock_security_data = true
development_endpoints = true

# Buhera Development Client
[clients.buhera]
[clients.buhera.endpoints]
environmental_service = "http://localhost:8446/environmental"
weather_data = "http://localhost:8446/weather"
coupling_analysis = "http://localhost:8446/coupling"

[clients.buhera.development]
mock_mode = true
simulate_weather_optimization = true
mock_environmental_data = true
development_endpoints = true

# Consciousness Development Client
[clients.consciousness]
[clients.consciousness.endpoints]
consciousness_service = "http://localhost:8447/consciousness"
alpha_wave_analysis = "http://localhost:8447/alpha"
neural_sync = "http://localhost:8447/neural"

[clients.consciousness.development]
mock_mode = true
simulate_fire_adaptation = true
mock_consciousness_data = true
development_endpoints = true

# Development Testing Configuration
[testing]
enabled = true
unit_tests_enabled = true
integration_tests_enabled = true
benchmark_tests_enabled = true
memorial_tests_enabled = true
precision_tests_enabled = true

[testing.test_data]
generate_test_coordinates = true
test_coordinate_count = 1000
test_precision_levels = ["Standard", "High", "Ultra", "Target"]
memorial_test_scenarios = true

[testing.mock_services]
mock_external_services = true
mock_quantum_services = true
mock_semantic_services = true
mock_auth_services = true
mock_environmental_services = true
mock_consciousness_services = true

# Development Performance Configuration
[performance]
cpu_optimization = false  # Disabled for easier debugging
memory_optimization = false
network_optimization = false
real_time_processing = false  # Relaxed for development
ultra_precision_mode = false  # Relaxed for development
development_performance_mode = true

# Development Security Configuration (Relaxed)
[security]
encryption_enabled = false  # Disabled for development
authentication_required = false  # Simplified for development
secure_communication = false
memorial_access_control = false  # Simplified for development
development_security_mode = true

# Development Debugging Configuration
[debugging]
enabled = true
debug_precision_calculations = true
debug_memorial_validation = true
debug_cosmic_significance = true
debug_predeterminism_proofs = true
debug_client_communications = true
debug_performance_metrics = true

[debugging.breakpoints]
precision_calculation_breakpoints = true
memorial_validation_breakpoints = true
cosmic_significance_breakpoints = true
client_communication_breakpoints = true

# Development Profiling Configuration
[profiling]
enabled = true
cpu_profiling = true
memory_profiling = true
network_profiling = true
precision_profiling = true
memorial_profiling = true

[profiling.output]
profile_output_directory = "profiles/dev"
cpu_profile_file = "cpu_profile.out"
memory_profile_file = "memory_profile.out"
precision_profile_file = "precision_profile.out"

# Development Hot Reload Configuration
[hot_reload]
enabled = true
watch_directories = ["src", "config"]
reload_on_config_change = true
reload_on_code_change = true
preserve_memorial_state = true

# Development API Configuration
[api]
enabled = true
bind_address = "127.0.0.1"
port = 8080
enable_cors = true
enable_swagger = true
debug_endpoints = true

[api.development]
expose_debug_endpoints = true
expose_internal_metrics = true
expose_memorial_debug_info = true
expose_precision_debug_info = true

# Development Visualization Configuration
[visualization]
enabled = true
precision_visualization = true
memorial_visualization = true
cosmic_significance_visualization = true
performance_visualization = true

[visualization.output]
visualization_directory = "visualizations/dev"
precision_charts = true
memorial_significance_charts = true
cosmic_alignment_charts = true
performance_charts = true

# Development Backup Configuration (Simplified)
[backup]
enabled = false  # Disabled for development
backup_interval = "1h"
backup_retention = "7d"  # Short retention for development
memorial_data_protection = true  # Always protect memorial data

# Development Environment Variables
[environment]
RUST_LOG = "debug"
RUST_BACKTRACE = "1"
MASUNDA_DEV_MODE = "true"
MASUNDA_DEBUG_PRECISION = "true"
MASUNDA_DEBUG_MEMORIAL = "true"
MASUNDA_MOCK_CLIENTS = "true"

# Development Feature Flags
[feature_flags]
enable_experimental_features = true
enable_debug_features = true
enable_development_tools = true
enable_mock_services = true
enable_performance_debugging = true
enable_memorial_debugging = true
enable_precision_debugging = true

# Development Notifications (Console only)
[notifications]
enabled = true
console_notifications = true
email_notifications = false  # Disabled for development
slack_notifications = false  # Disabled for development
memorial_notifications = true
precision_notifications = true

[notifications.development]
verbose_notifications = true
debug_notifications = true
memorial_debug_notifications = true
precision_debug_notifications = true
